# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47dc061324210f69c2e401df54731b96380e205d28155716b19830b8e390b92064f915463691de1e2e04fab69718dcbbf95fbb5e07e571705936a23313e00e33

test:
  secret_key_base: 1e0674f45cb0e38e3e5c1cc5a42de7edaf73e5ba43edbe45d5f8441f2e58e0dc87f159f1933ee03fe7add92de3bc2e6348ca8ecd13348042a105419f38934b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
